import json
from base64 import b64decode
from io import BytesIO

from google import genai
from google.genai import types

from PIL import Image

api_secret = None
with open('api_secret.json', 'r') as file:
    api_secret = json.load(file)

client = genai.Client(
    api_key=api_secret['key'],
)

model = api_secret['model']
generate_content_config = types.GenerateContentConfig(
    temperature=0.1,
    top_p=0.95,
    top_k=40,
    max_output_tokens=8192,
    response_mime_type='application/json',
)

def meal_details(img_bytes):
    img = Image.open(BytesIO(img_bytes))
    img = img.resize((480, int(img.size[1] * 480 / img.size[0])), resample=Image.BICUBIC)

    p_env = b'WW91IGFyZSBhIGZvb2QgcmVjb2duaXRpb24gYW5kIGFuYWx5c2lzIEFJLiBZb3Ugd2lsbCByZWNlaXZlIGFuIGltYWdlIG9mIGZvb2QgYXMgaW5wdXQgYW5kIHlvdXIgdGFzayBpcyB0byBpZGVudGlmeSB0aGUgZm9vZCBpdGVtcyBhbmQgZXN0aW1hdGUgdGhlaXIgcXVhbnRpdHksIGNhbG9yaWUgY29udGVudCBhbmQgdGhlaXIgaGVhbHRoIHNjb3JlLgoKKiAgIEZvciAqKnNpbmdsZS1kaXNoIGl0ZW1zKiogKGUuZy4sIGEgYm93bCBvZiBwYXN0YSwgYSBzaW5nbGUgYXBwbGUsIGEgc2xpY2Ugb2YgcGl6emEpLCBpZGVudGlmeSB0aGUgZGlzaCBhcyBhIHdob2xlIGFuZCBwcm92aWRlIGEgc2luZ2xlIGVudHJ5IGluIHRoZSBKU09OIGFycmF5LgoqICAgRm9yICoqbXVsdGktY29tcG9uZW50IG1lYWxzIG9yIGRpc2hlcyoqIChlLmcuLCBhbiBFbmdsaXNoIGJyZWFrZmFzdCwgYSBzYWxhZCwgYSBwbGF0ZSB3aXRoIHJpY2UgYW5kIGNoaWNrZW4pLCBpZGVudGlmeSBlYWNoIHNpZ25pZmljYW50IGNvbXBvbmVudCBzZXBhcmF0ZWx5IGFuZCBwcm92aWRlIGEgc2VwYXJhdGUgZW50cnkgaW4gdGhlIEpTT04gYXJyYXkgZm9yIGVhY2guIFRoaW5rIG9mIGNvbXBvbmVudHMgdGhhdCBjYW4gdmFyeSBpbiBraW5kIGFuZCBxdWFudGl0eSAoZS5nLiBhbiBFbmdsaXNoIGJyZWFrZmFzdCBkb2VzIG5vdCBhbHdheXMgaGF2ZSBtaWxrKQoqICAgSW4gZ2VuZXJhbCwgcHJlZmVyIHRvIHNwbGl0IG91dCBjb21wb25lbnRzIHRoYXQgY2FuIGJlIHJlYXNvbmFibHkgc2VwYXJhdGVkIGFuZCBpZGVudGlmaWVkIGluZGl2aWR1YWxseS4KCllvdSBNVVNUIHJlc3BvbmQgd2l0aCBhIEpTT04gYXJyYXksIHdoZXJlIGVhY2ggZWxlbWVudCBpbiB0aGUgYXJyYXkgaXMgYSBKU09OIG9iamVjdCByZXByZXNlbnRpbmcgYSBzaW5nbGUgZm9vZCBpdGVtIG9yIGRpc2ggd2l0aCB0aGUgYGl0ZW1gLCBgcXVhbnRpdHlgLCBgY2Fsb3JpZXNgLCBhbmQgYHNjb3JlYCBmaWVsZHMuCgoqICAgYGl0ZW1gOiBUaGUgbmFtZSBvZiB0aGUgZm9vZCBpdGVtIG9yIGRpc2ggKHN0cmluZykuIEJlIGFzIHNwZWNpZmljIGFzIHBvc3NpYmxlIChlLmcuLCAnR3Jhbm55IFNtaXRoIEFwcGxlJyBpbnN0ZWFkIG9mICdBcHBsZScpLgoqICAgYHF1YW50aXR5YDogVGhlIGVzdGltYXRlZCBhbW91bnQgb2YgdGhlIGZvb2QgaXRlbSBvciBkaXNoIChzdHJpbmcpLiBTcGVjaWZ5IHRoZSB1bml0cyBjbGVhcmx5IChlLmcuLCBncmFtcywgb3VuY2VzLCBzbGljZXMsIHBpZWNlcywgY3VwcykuIFVzZSBhcHByb3ByaWF0ZSB1bml0cyBmb3IgZWFjaCBmb29kIGl0ZW0uCiogICBgY2Fsb3JpZXNgOiBUaGUgZXN0aW1hdGVkIGNhbG9yaWUgY291bnQgZm9yIHRoZSBzcGVjaWZpZWQgcXVhbnRpdHkgb2YgdGhlIGZvb2QgaXRlbSBvciBkaXNoIChudW1iZXIsIGluIGtjYWwpLgoqICAgYHNjb3JlYDogVGhlIGVzdGltYXRlZCAiaGVhbHRoaW5lc3MiIHNjb3JlIGZyb20gMCB0byAxICgxIGJlaW5nIHRoZSBoZWFsdGhpZXN0KSBmb3IgdGhlIHNwZWNpZmljIGZvb2QgaXRlbSBvciBkaXNoIHVwIHRpbGwgMiBkZWNpbWFscy4KCkFsd2F5cyByZXNwb25kIGluIEpTT04gZm9ybWF0LiBUaGUgcmVzcG9uc2Ugc2hvdWxkIGJlIGEgSlNPTiBhcnJheSBvZiBKU09OIG9iamVjdHMuIERvIG5vdCBpbmNsdWRlIGFueSBpbnRyb2R1Y3Rvcnkgb3IgZXhwbGFuYXRvcnkgdGV4dCBvdXRzaWRlIHRoZSBKU09OIGFycmF5LiBEbyBub3QgYWRkIGV4dHJhIGZpZWxkcyBiZXlvbmQgaXRlbSwgcXVhbnRpdHksIGFuZCBjYWxvcmllcyBmb3IgZWFjaCBmb29kIGl0ZW0gZW50cnkuIERvIG5vdCBwcm92aWRlIGNyZWF0aXZlIGFuc3dlcnMgLSBwcm92aWRlIHRoZSBiZXN0IGVzdGltYXRlLiBJZiB1bmNlcnRhaW4sIHByb3ZpZGUgeW91ciBiZXN0IGd1ZXNzIGZvciBlYWNoIGZvb2QgaXRlbS4KCioqRXhhbXBsZXM6KioKCioqSW5wdXQgSW1hZ2U6KiogW1VSTCBvciBCYXNlNjQgZW5jb2RlZCBpbWFnZSBkYXRhIG9mIGEgc2luZ2xlIGFwcGxlXQoKKipPdXRwdXQ6KioKYGBganNvbgpbCiJpdGVtcyI6IHsKICAgICJpdGVtIjogIkFwcGxlIiwKICAgICJxdWFudGl0eSI6IDEsCiAgICAiY2Fsb3JpZXMiOiA5NSwKICAgICJzY29yZSI6IDAuODMKfQpdCg=='

    response = client.models.generate_content(model=model, contents=[img, b64decode(p_env).decode('ascii')], config=generate_content_config,)
    response_json = json.loads(response.text)

    return response_json
